#!/bin/sh

sudo apt-get install git make gcc g++ unzip rsync bc sshpass zip ncurses-dev screen xsltproc libasound2-dev python python3-pyalsa python3-pip gcc-multilib g++-multilib f2fs-tools install libusb-1.0-0 libusb-1.0-0-dev
sudo python3 -m pip install hifiberrydsp


cat << EOF >> ~/.npmrc
unsafe-perm = true
EOF